from matematika3 import *
def main():
	a,b,x=max2(2,5)
	print("Max2 --> {} dan {}    :{} ".format(a,b,x))
	a,b,c,x=max3(1,2,5)
	print("Max3 --> {}, {}, dan {}:{} ".format(a,b,c,x))
	a,b,c,d,x=max4(1,2,5,7)
	print("Max4 --> {}, {}, {}, {} :{} ".format(a,b,c,d,x))
	n,pri1=IsPrima(7)
	print("IsPrima {}           :{}".format(n,pri1))
	n,pri2=IsPrima(17)
	print("IsPrima {}          :{}".format(n,pri2))
	n,pri3=IsPrima(70)
	print("IsPrima {}          :{}".format(n,pri3))
	x,y,fpb1=FPB(36,48)
	print('FPB ({},{})         :{}'.format(x,y,fpb1))
	n,gan1=IsGanjil(93)
	print("IsGanjil {}         :{}".format(n,gan1))
	n,gan2=IsGanjil(1324)
	print("IsGanjil {}       :{}".format(n,gan2))
	basis,eksp,pangkat1=Pangkat(2,8)
	print('Pangkat({},{})        :{}'.format(basis,eksp,pangkat1))
	n,nop1=NumOfPrima(15)
	print('NumOfPrima ({})     :{}'.format(n,nop1))
	N,son1=SumOfN(15)
	print('SumOfN ({})         :{}'.format(N,son1))
	N,pon1=ProductOfN(15)
	print('ProductOfN ({})     :{}'.format(N,pon1))
	N,asn1=AveSumOfN(15)
	print('AveSumOfN ({})      :{}'.format(N,asn1))
	N,apn1=AveProdOfN(15)
	print('AveProdOfN ({})     :{}'.format(N,apn1))
	C,c2f1=C2F(72.50)
	print('{} C  adalah {} F'.format(C,c2f1))
	F,f2c1=F2C(13.50)
	print("{:.2f} F adalah {:.2f} C".format(F,f2c1))
	C,c2r1=C2R(72.50)
	print("{} C  adalah {} R".format(C,c2r1))
	R,r2c1=R2C(22.50)
	print("{} R  adalah {} C".format(R,r2c1))
	Cal,c2k1=Cel2Cal(72.50)
	print("{} C  adalah {} K".format(Cal,c2k1))
	C,k2c1=Cal2Cel(172.50)
	print("{} K adalah {} C".format(C,k2c1))
	R,r2f1=R2F(72.50)
	print("{} R  adalah {} F".format(R,r2f1))
	F,f2r1=F2R(62.50)
	print('{} F  adalah {:.2f} R'.format(F,f2r1))



if __name__ == '__main__':
	main()